global:
  scrape_interval: 60s
  scrape_timeout: 10s
  evaluation_interval: 15s
alerting:
  alertmanagers:
  - static_configs:
    - targets: []
    scheme: http
    timeout: 10s
    api_version: v1
scrape_configs:
- job_name: node-exporter
  honor_timestamps: true
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets: ['localhost:9100']
    labels:
      instance: 'Monitoring machine'

  - targets: ['34.41.96.172:9100']
    labels:
      instance: 'Blume AI'

  - targets: ['public.blume.mahoudev.com:9100']
    labels:
      instance: 'Blume Proxy'